{% set version = "1.2.3" %}

package:
    name: mss
    version: {{ version }}

source:
    fn: mss-{{ version }}.tar.gz
    url: https://bitbucket.org/wxmetvis/mss/get/{{ version }}.tar.gz
    sha256: 7823c2b4391ffe75b9e1302281d13e1c2d8683d737c1931b964a83d0d96d3763

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt
    skip: True  # [py3k]
    entry_points:
      - mss = mslib.msui.mss_pyui:main
      - mswms = mslib.mswms.mswms:main

requirements:
    build:
        - python
        - setuptools
    run:
        # Relaxed versions of the run dependencies for conda-forge.
        - python
        - basemap 1.0.7
        - chameleon
        - execnet
        - lxml
        - netcdf4
        - paste
        - pillow
        - python-dateutil
        - pytz
        - requests
        - scipy
        - six
        - tk 8.5.*
        # FIXME: Workaround until https://github.com/conda-forge/matplotlib-feedstock/issues/36 is fixed.
        - icu 56.*

test:
    imports:
        - mslib
    commands:
        - mswms -h

about:
    summary: A web service based tool to plan atmospheric research flights
    home: https://bitbucket.org/wxmetvis/mss
    license: Apache 2.0
    license_file: LICENSE

extra:
    recipe-maintainers:
        - ReimarBauer
