{% set version = "1.4.1" %}

package:
  name: mss
  version: {{ version }}

source:
  fn: mss-{{ version }}.tar.gz
  url: https://bitbucket.org/wxmetvis/mss/get/{{ version }}.tar.gz
  sha256: 57c0f0c330a8c6ae7346af58d74c4af1191a21ff903f1810f8c75c2fa9418640

build:
  number: 0
  skip: True  # [py3k]
  entry_points:
    - mss = mslib.msui.mss_pyui:main
    - mswms = mslib.mswms.mswms:main
    - demodata = mslib.mswms.demodata:main

requirements:
  build:
    - python
    - setuptools
    - menuinst  # [win]
  run:
    - python
    - menuinst  # [win]
    - basemap 1.0.7
    - chameleon
    - execnet
    - lxml
    - netcdf4
    - hdf4 4.2.12
    - paste
    - pillow
    - python-dateutil
    - pytz
    - pyqt 4.11.*  # [osx]
    - qt 4.8.*  # [osx]
    - requests
    - scipy
    - six
    - tk 8.5.*
    - pykml

test:
  imports:
    - mslib
  commands:
    - mswms -h
    - mss -h

about:
  summary: 'A web service based tool to plan atmospheric research flights.'
  home: https://bitbucket.org/wxmetvis/mss
  license: Apache 2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ReimarBauer
