# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Tc7/phJ9qo5C4TorVRr8xN8JTqSM4+3Ql87CM1xG7Wf8e/NEumKkL3vzUiapA+j435F2ddeuOb+aLucNvpzHqPhEprG7JqirVY0Er6Lq3haJY9R7IxFDf7KMBrTOqROslfsjIBqFRKPsJ9wjzj1PvlxEJGG9/xuxASUhzrSZ3qFygKaQhCjL/CdA4TDLn7tQTarjxzrBHMlLfY39mWicl57Ua3Vnmoc84oTC7HiSlrroATujP51JGYB5J9UtvQJOYstzQEVQOWczqSV6WzRUkWIEzY1NxQCpn9erps2MdVsWsm7OuVa9odwXIrzwErof7PZZDCzheK2axW2uMih1QHSYYZazARBEXMW0N/Du5nHbBl4VCaCr4JFI65CNqMQbzopokPIWxdTgBl7KAiSzfhXxMjCxiXKp4uyFqP84pzLvJ/9zCOEAd+0VYfI8j2eNzljSs/ByevhnYSGa7ClRcSpBLo9Ag/i+gdNFG9nVQ/2wSIrXcXce0jII67AOtANjVTyT/n83/06109rzZ16EN/GO5MaPyUIK6Ya6cDW1tv82SnnSQiCrPhRMLFqu6kmAbzNnQKuig5HiEk+A6KZW1p3l3qlSjfbJSIW50tGAHha4B9ku9vE7CxnxaKYYwm5iLgebtQI3Vx1OgB4yemtPG490nfPwlYqHG92XmUjGtt0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
