travis:
  secure:
    BINSTAR_TOKEN: jwcp9FNUEdpPW3Ab/lmBt576PjulStlQCilS/tG4u2iTTauoX9qQyuXIXUCgIhxHV7U8kUxx/Kfyk+2ohDaKA9fJp0c9LeXuWRbaDenCKUug9Hdl877lppEgnVwNgKA3eniom8gTj2UCP6S90gqyHHsvKLYIOoIwtpbVCAjM4159UqG7+3VG7CUnaztbuytIYKF6uA8cIKnricMfcWUAY8M1Y2wKanGrxsNgyeISXGthSwkMU+XDzDJF90L/otL7OeuY5JXLNCs9WU2kAxLbp9zlYODF1ttCwsX1Ijiy/fwfoOA5n4gC9rf/2C2JgLG4ShVfkMneY36K064ELltfhZHR5te7Qw2EoxYAKKsOp9DG/r37p7PIcDg16VpS5JcZjUUBLslE6tN4P9Y8Ov9H6dXZ4RSX9W5nBwL56BWpIn5rAtconeV5Jm5RWlzNADgdLPaL94WILExwC5Vnjqos68UFWb4EPZbjHsIQaRWzs+n0+Ij/qG3djJmQorHqmOv1MU4j7Osnre/qQxx0rIiIKn20TWmNIvMF6dGBgcC5R8kC0f2TRI2gHSVwCcmI+JtQOr4dRPBlb2v45099DtZJRcmGoqieTW407ZAlGfrVHeRJrXTW+ZDG4tf4F/KOO9njJfVGfnCPmeth6MNKlWI/XhTNRNLLk/jNoQIWb73aeL8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
