travis:
  secure:
    BINSTAR_TOKEN: Tc7/phJ9qo5C4TorVRr8xN8JTqSM4+3Ql87CM1xG7Wf8e/NEumKkL3vzUiapA+j435F2ddeuOb+aLucNvpzHqPhEprG7JqirVY0Er6Lq3haJY9R7IxFDf7KMBrTOqROslfsjIBqFRKPsJ9wjzj1PvlxEJGG9/xuxASUhzrSZ3qFygKaQhCjL/CdA4TDLn7tQTarjxzrBHMlLfY39mWicl57Ua3Vnmoc84oTC7HiSlrroATujP51JGYB5J9UtvQJOYstzQEVQOWczqSV6WzRUkWIEzY1NxQCpn9erps2MdVsWsm7OuVa9odwXIrzwErof7PZZDCzheK2axW2uMih1QHSYYZazARBEXMW0N/Du5nHbBl4VCaCr4JFI65CNqMQbzopokPIWxdTgBl7KAiSzfhXxMjCxiXKp4uyFqP84pzLvJ/9zCOEAd+0VYfI8j2eNzljSs/ByevhnYSGa7ClRcSpBLo9Ag/i+gdNFG9nVQ/2wSIrXcXce0jII67AOtANjVTyT/n83/06109rzZ16EN/GO5MaPyUIK6Ya6cDW1tv82SnnSQiCrPhRMLFqu6kmAbzNnQKuig5HiEk+A6KZW1p3l3qlSjfbJSIW50tGAHha4B9ku9vE7CxnxaKYYwm5iLgebtQI3Vx1OgB4yemtPG490nfPwlYqHG92XmUjGtt0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
